name: Publish Docker image

on:
  release:
    types: [published]

jobs:

  build_and_pub:

    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build

      - name: Push tagged image to docker.io
        run: |
          CURRENT_NAME="$(docker images -q | head -n 1)"
          VERSION_TAG="${GITHUB_REF:11}"
          BASE_NAME="$USERNAME/grading-node"
          CURRENT_TAG="$BASE_NAME:$VERSION_TAG"
          LATEST_TAG="$BASE_NAME:latest"
          docker tag "$CURRENT_NAME" "$CURRENT_TAG"
          docker tag "$CURRENT_NAME" "$LATEST_TAG"
          docker push "$CURRENT_TAG"
          docker push "$LATEST_TAG"